### ISSUE TITLE
None of the Invite links work anymore

### ISSUE THREAD

**Issue by coolaj86** [nh-server/nh-server.github.io#1]
All of these sites have discord invite links. All of them are invalid.

- https://nintendohomebrew.com/
- https://github.com/nh-server/
- https://nintendobrew.github.io/

**Comment by coolaj86** [comment]
Follow up question / clarification:

Could I get an invite link, please? 😁

**Comment by ihaveamac** [comment]
The invite links work fine, if they appear invalid then you are probably banned.

**Comment by coolaj86** [comment]
I don't believe that I've ever joined before, how could I be banned?

For reference: If you google "GameCube Homebrew" my "for N00bs" article and "Everything GameCube Homebrew" video on are the first page of results - and perhaps the first hit.

<img width="1112" alt="Screen Shot 2021-04-19 at 9 32 39 AM" src="https://user-images.githubusercontent.com/122831/115262923-35330d00-a0f2-11eb-837e-c0d7f90c451a.png">

That's organic, from people are linking to it and sharing it. I'm not very involved in the modding community at large (just started figuring it out for myself about 2 years ago maybe), but I hope that having some high quality content the most referenced content would lend me a little street cred.

**Comment by coolaj86** [comment]
Actually, I just tried again - same account (coolaj86) - and today it's working.
